// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_zAlQU2b9OFNZJGm0MJfv-RsSi6Kg4E',
    appId: '1:515752214210:android:6d1914e73eb665e170855b',
    messagingSenderId: '515752214210',
    projectId: 'missiontimerdev',
    storageBucket: 'missiontimerdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTKEbVAos9TO7iMr2fbdhBheqB7vfuMbQ',
    appId: '1:515752214210:ios:296360433e66bfe170855b',
    messagingSenderId: '515752214210',
    projectId: 'missiontimerdev',
    storageBucket: 'missiontimerdev.appspot.com',
    iosClientId: '515752214210-28o31553bgsataqp26a991lfo6fa6n84.apps.googleusercontent.com',
    iosBundleId: 'flu.gonosen.missionTimer',
  );
}
